spring:
  application:
    name: springboot-poc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_poc?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'false'
        auto_quote_keyword: 'true'
        show_sql: 'true'
        default_batch_fetch_size: 10
    database-platform: org.hibernate.dialect.MySQLDialect